### ISSUE TITLE
Exception on OrderExample

### ISSUE THREAD

**Issue by wir33658** [eligosource/eventsourced#25]
Hi, I get the following exception on the OrderExample (wip-akka-2.1 branch) :

Exception in thread "main" c487df01-d62d-4807-8c83-1367c8e9acebakka.actor.InvalidActorNameException: illegal actor name 'validation requests', must conform to (?:[-\w:@&=+,.!~_'_;]|%\p{XDigit}{2})(?:[-\w:@&=+,.!~_'$_;]|%\p{XDigit}{2})*
    at akka.actor.dungeon.Children$class.checkName(Children.scala:166)
    at akka.actor.dungeon.Children$class.attachChild(Children.scala:43)
    at akka.actor.ActorCell.attachChild(ActorCell.scala:301)
    at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:513)
    at org.eligosource.eventsourced.core.ReliableChannelProps.createChannel(EventsourcingExtension.scala:404)
    at org.eligosource.eventsourced.core.EventsourcingExtension.channelOf(EventsourcingExtension.scala:187)
    at org.eligosource.eventsourced.example.OrderExample$delayedInit$body.apply(OrderExample.scala:43)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:309)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.App$class.main(App.scala:71)
    at org.eligosource.eventsourced.example.OrderExample$.main(OrderExample.scala:28)
    at org.eligosource.eventsourced.example.OrderExample.main(OrderExample.scala)

**Comment by krasserm** [comment]
Thanks for reporting, this is now fixed in master (branch wip-akka-2.1 has been merged into it yesterday). Reason was that channel names are now also used for the underlying actor name which was introduced with [this commit](https://github.com/eligosource/eventsourced/commit/6e1ce20b5550b7dcec57ae9a9f41e4b043f8fb81).
